config/routes.rb
Rails.application.routes.draw do
  get "/auth/github/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"
  resources :repos, only: [:index] do
    resource :activation, only: [:create, :destroy]
  end
  resources :repo_syncs, only: [:create]
  resources :builds, only: [:create]
  root to: "home#index"
end

app/models/repo.rb
class Repo < ApplicationRecord
  belongs_to :owner
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships
  has_many :builds, dependent: :destroy

  validates :github_id, numericality: { greater_than: 0 }, uniqueness: true
  validates :hook_id, numericality: { greater_than: 0 }, allow_nil: true

  def organization
    name.split("/").first
  end

  def self.active
    where(active: true)
  end

  def self.with_membership_status
    select("repos.*", "memberships.admin AS admin_membership")
  end

  def self.upsert(github_id:, private:, name:, in_organization:, owner:)
    repo = find_or_initialize_by(github_id: github_id)
    attrs = {
      private: private,
      name: name,
      in_organization: in_organization,
      owner: owner
    }

    if repo.update(attrs)
      repo
    else
      Rails.logger.error("Error upserting repo: #{repo.error_messages_formatted}")
      nil
    end
  end

  def remove_membership(user)
    users.destroy(user)
  end
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  before_action :load_repos_by_organization

  def index
  end

  private

  def load_repos_by_organization
    @repos_by_organization = current_user.repos.with_membership_status.
      order("memberships.admin DESC").
      order(active: :desc).
      order(Repo.arel_table["name"].lower.asc).
      group_by(&:organization)
  end
end

app/views/repos/_repo.html.haml
%li.repo{ id: dom_id(repo), class: ("repo--active" if repo.active?) }
  .repo-name
    = repo.name
  .repo-activation-toggle
    - if !repo.admin_membership?
      .repo-restricted
        Only repo admins can activate
    - elsif repo.active?
      = form_with(model: repo, url: repo_activation_path(repo), method: :delete) do |form|
        = form.submit "Active", class: "repo-toggle", onmouseover: "this.value='Deactivate';", onmouseout: "this.value='Active';"
    - else
      = form_with(model: repo, url: repo_activation_path(repo), method: :post) do |form|
        = form.submit "Activate", class: "repo-toggle"

app/views/repos/_tools.html.haml
.repo-tools
  .repo-tools-refresh
    -# %button.repo-tools-refresh-button
    -#   Refresh repo list
    = form_with(url: repo_syncs_path, method: :post) do |form|
      = form.submit "Refresh repo list", class: "repo-tools-refresh-button"

app/views/repos/index.html.haml
= render partial: "tools"
%section.organizations
  - @repos_by_organization.each do |organization, repos|
    .organization
      %header.organization-header
        %h2.organization-header-title
          = organization
      %section.repo_listing
        %ul.repos
          - repos.each do |repo|
            = render(repo)